#ifndef STRUCTS_H
#define STRUCTS_H

typedef enum{SYSTEM,MQTT,TASK,ARGUMENT}PACK_NAME;
typedef struct sys_pack_t
{
    bool reboot;
    bool memory;
    bool led;
    bool key_reg;
    bool battery;
    bool speaker;

}sys_pack_t;

typedef enum show_slots
{
    no_slots=-1,
    hmac1,
    sha1,
    sha256,
    rsa_key,
    rsa_public_encrypt,
    rsa_private_decrypt,
    rsa_private_encrypt,
    rsa_public_decrypt,
    rsa_private_sign,
    rsa_public_verify,
    sm2_public_encrypt,
    sm2_private_decrypt,
    sha1_encrypt,
    sha256_encrypt,
    socket_connect,
    socket_send,
    socket_rec,
    ota_http_update,
    ota_triggle_update,
    ota_state_check,
    ota_end_update,
    sys_reboot,
    sys_memory_handle,
    SYS_MEMORY_CALLOC,
    SYS_BUTTON,
    SYS_BUTTON_UNREG,
    SYS_MEMORY_RELLOC,
    SYS_MEMORY_FREE,
    SYS_LED_SET,
    SYS_LED_GET,
    SYS_BATTERY,
    SYS_SPEAKER,
    SYS_LIBVERSION,
    SYS_SDKVERSION,
    sys_led,
    sys_key_press_reg,

    mqtt_connect,
    mqtt_disconnect,
    MQTT_CLoSE,
    mqtt_publish,
    mqtt_subscribe,
    mqtt_unsubscribe,
    task_create,
    task_del,
    task_msg_queue_create,
    task_msg_send,
    task_msg_recv,
    task_msg_reset,
    task_msg_del,
    task_seamphere_create,
    task_seamphere_take,
    task_seamphere_give,
    task_seamphere_del,
    arg_read,
    arg_write,
    arg_str_read,
    arg_str_write,
    time_set,
    time_gets,
    GET_TASK_TICK,
    TIME_CREATE,
    TIME_STOP,
    TIME_OPEN,
    TIME_DELETE,
    TASK_CREATE,
    TASK_DELETE,
    QUEUE_CREATE,
    QUEUE_DELETE,
    MSG_SEND,
    MSG_RECEIVE,
    MSG_DELETE,
    MSG_RESET,
    SEMAPHORE_CREATE,
    SEMAPHORE_TAKE,
    SEMAPHORE_FREE,
    SEMAPHORE_DELETE,
    PARAM_INT_READ,
    PARAM_INT_WRITE,
    PARAM_STR_READ,
    PARAM_STR_WRITE,
    TTS_SET_SPEED,
    TTS_SET_PITCH,
    TTS_BEEP_PLAYER,
    TTS_PLAY_AUDIOS,
    TTS_PLAY_AUDIOS_STRING,
    TTS_CHECK_STATE,
    HEX_TO_ASC,
    ASC_TO_HEX,
    ASC_TO_BCD,
    BCD_TO_ASC,
    GBK_TO_UTF,
    UTF_TO_GBK,
    URL_ENCODE,
    URL_DECODE,
    HEX_TO_DEC,
    ASC_TO_INT,
    BCD_TO_INT,
    INT_TO_BCD,
    TLV_BUILD,
    TLV_DESTORY,
    BCDTOUINT64,
    UINTTOC4,
    C2TOINT,
    C4TOUINT,
    CSTRLCPY,
    GETRAND,
    GETTIMERSTAMP,
    STRCASECMP,
    STRREMOVECHAR,
    PARAM_DELETE_DATA,
    HTTP_GET,
    HTTP_POST,
    MODULEGETPOSTNAME,
    MODULEGETQUALITY,
    MODULEGETSTATUS,
    MODULEDISCONNECT,
    SNTPSTART,
    WIFIGETAPINFO,
    WIFIGETMAC,
    WIFIGETQUALITY,
    WIFIGETSTATUS,
    WIFIGETVERSION,
    WIFISETMAC,
    WIFISETNETWORK,
    GETLOCALIP




}show_slots;

#endif // STRUCTS_H
